parameters:
#    garniture_radio.example.class: Garniture\RadioBundle\Example

services:
#    garniture_radio.example:
#        class: %garniture_radio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
